/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface SourceMap {
  file?: string
  mappings: string
  names: Array<string>
  sourceRoot?: string
  sources: Array<string>
  sourcesContent?: Array<string>
  version: number
  x_google_ignoreList?: Array<number>
}
export declare class FakeJsPlugin {
  constructor(sourcemap: boolean, cjsDefault: boolean, sideEffects: boolean)
  transform(code: string, id: string): TransformResult
  renderChunk(code: string, fileName: string, moduleIds: Array<string>): RenderChunkResult
}

export interface RenderChunkResult {
  code: string
  map?: SourceMap
  errors?: Array<string>
}

export interface TransformResult {
  code: string
  map?: SourceMap
  errors?: Array<string>
}
