/**
 * Generated by tsnapi — public API snapshot of `rolldown-plugin-dts`
 */
// #region Interfaces
export interface Options extends GeneralOptions, TscOptions {
  oxc?: boolean | Omit<IsolatedDeclarationsOptions, "sourcemap">;
  tsgo?: boolean | TsgoOptions;
}
// #endregion

// #region Functions
export declare function createFakeJsPlugin(_: Pick<OptionsResolved, "sourcemap" | "cjsDefault" | "sideEffects">): Plugin;
export declare function createGeneratePlugin(_: Pick<OptionsResolved, "entry" | "cwd" | "tsconfig" | "tsconfigRaw" | "build" | "incremental" | "oxc" | "emitDtsOnly" | "vue" | "tsMacro" | "parallel" | "eager" | "tsgo" | "newContext" | "emitJs" | "sourcemap">): Plugin;
export declare function dts(_?: Options): Plugin[];
export declare function resolveOptions(_: Options): OptionsResolved;
// #endregion