/**
 * Generated by tsnapi — public API snapshot of `rolldown-plugin-dts`
 */
// #region Interfaces
export interface Options extends GeneralOptions, TscOptions {
  oxc?: boolean | Omit<IsolatedDeclarationsOptions, "sourcemap">;
  tsgo?: boolean | TsgoOptions;
}
// #endregion

// #region Functions
export declare function createFakeJsPlugin({
  sourcemap,
  cjsDefault,
  sideEffects
}: Pick<OptionsResolved, "sourcemap" | "cjsDefault" | "sideEffects">): Plugin;
export declare function createGeneratePlugin({
  entry,
  tsconfig,
  tsconfigRaw,
  isTsconfigOverridden,
  build,
  incremental,
  cwd,
  oxc,
  emitDtsOnly,
  vue,
  tsMacro,
  parallel,
  eager,
  tsgo,
  newContext,
  emitJs,
  sourcemap
}: Pick<OptionsResolved, "entry" | "cwd" | "tsconfig" | "tsconfigRaw" | "isTsconfigOverridden" | "build" | "incremental" | "oxc" | "emitDtsOnly" | "vue" | "tsMacro" | "parallel" | "eager" | "tsgo" | "newContext" | "emitJs" | "sourcemap">): Plugin;
export declare function dts(_?: Options): Plugin[];
export declare function resolveOptions({
  entry,
  cwd,
  dtsInput,
  emitDtsOnly,
  tsconfig,
  tsconfigRaw: overriddenTsconfigRaw,
  compilerOptions: overriddenCompilerOptions,
  sourcemap,
  resolver,
  cjsDefault,
  sideEffects,
  build,
  incremental,
  vue,
  tsMacro,
  parallel,
  eager,
  newContext,
  emitJs,
  oxc,
  tsgo
}: Options): OptionsResolved;
// #endregion