/**
 * Generated by tsnapi — public API snapshot of `rolldown-plugin-dts/internal`
 */
// #region Functions
export declare function filename_dts_to(_: string, _: "js" | "ts"): string;
export declare function filename_js_to_dts(_: string): string;
export declare function filename_to_dts(_: string): string;
export declare function replaceTemplateName(_: string, _: string): string;
export declare function resolveTemplateFn(_: string | ChunkFileNamesFunction, _: PreRenderedChunk): string;
// #endregion

// #region Variables
export declare const RE_CSS: RegExp;
export declare const RE_DTS: RegExp;
export declare const RE_DTS_MAP: RegExp;
export declare const RE_JS: RegExp;
export declare const RE_JSON: RegExp;
export declare const RE_NODE_MODULES: RegExp;
export declare const RE_ROLLDOWN_RUNTIME: RegExp;
export declare const RE_TS: RegExp;
export declare const RE_VUE: RegExp;
// #endregion

// #region Other
export { readTsconfig }
// #endregion