/**
 * Generated by tsnapi — public API snapshot of `rolldown-plugin-dts/tsc`
 */
// #region Interfaces
export interface TscModule {
  program: ts.Program;
  file: ts.SourceFile;
}
export interface TscOptions extends Required<Pick<Options, "build" | "cwd" | "incremental" | "sourcemap" | "tsconfigRaw">>, Pick<Options, "tsconfig" | "tsMacro" | "vue"> {
  tsconfig?: string;
  entries?: string[];
  id: string;
  context?: TscContext;
}
export interface TscResult {
  code?: string;
  map?: SourceMapInput;
  error?: string;
}
// #endregion

// #region Functions
export declare function tscEmit(_: TscOptions): TscResult;
// #endregion