/**
 * Generated by tsnapi — public API snapshot of `rolldown-plugin-dts/tsc`
 */
// #region Interfaces
export interface TscModule {
  program: ts.Program;
  file: ts.SourceFile;
}
export interface TscOptions {
  tsconfig?: string;
  tsconfigRaw: TsconfigJson;
  cwd: string;
  build: boolean;
  incremental: boolean;
  entries?: string[];
  id: string;
  sourcemap: boolean;
  vue?: boolean;
  tsMacro?: boolean;
  context?: TscContext;
}
export interface TscResult {
  code?: string;
  map?: SourceMapInput;
  error?: string;
}
// #endregion

// #region Functions
export declare function tscEmit(_: TscOptions): TscResult;
// #endregion